pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: ./models/models--arminhaberl--diarize/snapshots/70180675a7e49a2d26bd3eaff33b969250cad8dc/embedding_pyannote.bin
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: ./models/models--arminhaberl--diarize/snapshots/70180675a7e49a2d26bd3eaff33b969250cad8dc/segmentation_pyannote.bin
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
    threshold: 0.4442333667381752
